#!/usr/bin/env python
# encoding: utf-8
"""
Constants.py
"""

import sys

SPACESHIP_SIZE = SPACESHIP_WIDTH, SPACESHIP_HEIGHT = 80, 80
SPACESHIP_COLLISION = SPACESHIP_COL_WIDH, SPACESHIP_COL_HEIGHT = 30, 65

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1200, 800
BACKGROUND_POSITION = (0,0)

PHASES = 3
START_PHASE = 0

SPACESHIP_SPEED = 8
SPACESHIP_INITIAL_POS = 600, 400
SPACESHIP_INITIAL_PROJECTILES = 25

PROJECTILE_SIZE = PROJECTILE_WIDTH, PROJECTILE_HEIGHT = 25, 25
PROJECTILE_SPEED = 12

METEOR_SPEED = [10, 7, 5]
METEOR_SIZES = [1, 2, 3]
METEOR_SIZE_MULTIPLIER = 22
METEOR_COLLISION_MULTIPLIER = 17

METEOR_INITIAL_Y = 0

ASTEROIDS_PER_LEVEL = [15, 20, 25, 30]
TIME_PER_LEVEL =  30 * 1000 #in milliseconds.

TEXT_FONT = 'freesansbold.ttf'
TEXT_SIZE = 32
BULLET_COUNTER_POSITION = 90, 50
TIMER_POSITION = 90, 100